string(REPLACE "," ";" _libs "${LIBS}")

set(_body "")
set(_count 0)
foreach (_lib IN LISTS _libs)
    execute_process(COMMAND "${NM}" --defined-only --extern-only "${_lib}" OUTPUT_VARIABLE _out RESULT_VARIABLE _rc)
    if (NOT _rc EQUAL 0)
        message(FATAL_ERROR "llvm-nm failed on ${_lib}")
    endif ()
    string(REPLACE "\n" ";" _lines "${_out}")
    foreach (_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        if (_line MATCHES "^[0-9a-fA-F]+ ([TDBRC]) (.+)$")
            set(_kind "${CMAKE_MATCH_1}")
            set(_name "${CMAKE_MATCH_2}")
            if (_name MATCHES "^[?$]" OR _name MATCHES "^__" OR _name MATCHES "^_CRT" OR _name MATCHES "^\\.")
                continue()
            endif ()
            if (DEFINED _seen_${_name})
                continue()
            endif ()
            set(_seen_${_name} 1)
            if (_kind STREQUAL "T")
                string(APPEND _body "  ${_name}\n")
            else ()
                string(APPEND _body "  ${_name} DATA\n")
            endif ()
            math(EXPR _count "${_count}+1")
        endif ()
    endforeach ()
endforeach ()
file(WRITE "${OUT}" "EXPORTS\n${_body}")
message(STATUS "generated ${OUT} with ${_count} exports")
